[DEBUG|logging_pack.py:45] 2021-05-18 15:32:03,072 > debug 모드!
[INFO|logging_pack.py:46] 2021-05-18 15:32:03,079 > info 모드!
[WARNING|logging_pack.py:47] 2021-05-18 15:32:03,079 > warning 모드!
[ERROR|logging_pack.py:48] 2021-05-18 15:32:03,079 > error 모드!
[CRITICAL|logging_pack.py:49] 2021-05-18 15:32:03,080 > critical 모드!
[DEBUG|open_api.py:309] 2021-05-18 15:32:29,966 > connected
[DEBUG|open_api.py:250] 2021-05-18 15:32:29,966 > account_info 함수에 들어왔습니다!
[DEBUG|open_api.py:257] 2021-05-18 15:32:29,966 > get_login_info 함수에 들어왔습니다!
[DEBUG|open_api.py:253] 2021-05-18 15:32:29,967 > 계좌번호 : 8164053811
[DEBUG|open_api.py:166] 2021-05-18 15:32:29,967 > variable_setting 함수에 들어왔다.
[DEBUG|open_api.py:180] 2021-05-18 15:32:29,967 > 모의투자 1!!
[DEBUG|open_api.py:213] 2021-05-18 15:32:29,967 > db name !!! : JackBot1_imi1
[DEBUG|open_api.py:204] 2021-05-18 15:32:30,148 > JackBot1_imi1 데이터 베이스가 존재한다! 
[DEBUG|open_api.py:84] 2021-05-18 15:32:30,203 > self.sf.simul_num(알고리즘 번호) : 1
[DEBUG|open_api.py:85] 2021-05-18 15:32:30,204 > self.sf.db_to_realtime_daily_buy_list_num : 1
[DEBUG|open_api.py:86] 2021-05-18 15:32:30,204 > self.sf.sell_list_num : 1
[DEBUG|open_api.py:92] 2021-05-18 15:32:30,239 > setting_data db 존재한다!!!
[DEBUG|open_api.py:1468] 2021-05-18 15:32:30,295 > get_d2_deposit 함수에 들어왔습니다!
[DEBUG|open_api.py:1134] 2021-05-18 15:32:30,296 > 1
[DEBUG|open_api.py:296] 2021-05-18 15:32:30,339 > _receive_msg 함수에 들어왔습니다!
[DEBUG|open_api.py:304] 2021-05-18 15:32:30,339 > [00Z310] 모의투자 조회가 완료되었습니다
[DEBUG|open_api.py:1479] 2021-05-18 15:32:30,342 > _opw00001!!!
[DEBUG|open_api.py:1483] 2021-05-18 15:32:30,343 > 예수금!!!!
[DEBUG|open_api.py:1484] 2021-05-18 15:32:30,344 > 000000045982814
[DEBUG|open_api.py:541] 2021-05-18 15:32:30,346 > check_balance 함수에 들어왔습니다!
[DEBUG|open_api.py:1134] 2021-05-18 15:32:30,904 > 2
[DEBUG|open_api.py:296] 2021-05-18 15:32:30,927 > _receive_msg 함수에 들어왔습니다!
[DEBUG|open_api.py:304] 2021-05-18 15:32:30,927 > [00Z310] 모의투자 조회가 완료되었습니다
[DEBUG|open_api.py:1632] 2021-05-18 15:32:30,931 > _opw00018!!!
[DEBUG|collector_api.py:38] 2021-05-18 15:32:33,067 > code_update_check 함수에 들어왔습니다.
